services:
  postgres:
    image: postgres:15
    container_name: inventory
    environment:
      POSTGRES_USER: anopa
      POSTGRES_PASSWORD: rusamu2003!!
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      - pgnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@bezy.com
        PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
        - "5050:80"
    depends_on:
        - postgres
    networks:
        - pgnet

  app:
    build: ./
    depends_on:
    - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory
      SPRING_DATASOURCE_USERNAME: anopa
      SPRING_DATASOURCE_PASSWORD: rusamu2003!!
    ports:
      - "8080:8080"

volumes:
  postgres_data:
networks:
  pgnet:
    driver: bridge

