spring.application.name=inventory-system
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=anopa
spring.datasource.password=rusamu2003!!

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
